// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	compare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	types "github.com/aws-controllers-k8s/runtime/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// AWSResourceDescriptorWithPreDeleteDelta is an autogenerated mock type for the AWSResourceDescriptorWithPreDeleteDelta type
type AWSResourceDescriptorWithPreDeleteDelta struct {
	mock.Mock
}

// DeltaForPreDelete provides a mock function with given fields: a, b
func (_m *AWSResourceDescriptorWithPreDeleteDelta) DeltaForPreDelete(a types.AWSResource, b types.AWSResource) (*compare.Delta, types.AWSResource) {
	ret := _m.Called(a, b)

	if len(ret) == 0 {
		panic("no return value specified for DeltaForPreDelete")
	}

	var r0 *compare.Delta
	var r1 types.AWSResource
	if rf, ok := ret.Get(0).(func(types.AWSResource, types.AWSResource) (*compare.Delta, types.AWSResource)); ok {
		return rf(a, b)
	}
	if rf, ok := ret.Get(0).(func(types.AWSResource, types.AWSResource) *compare.Delta); ok {
		r0 = rf(a, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compare.Delta)
		}
	}

	if rf, ok := ret.Get(1).(func(types.AWSResource, types.AWSResource) types.AWSResource); ok {
		r1 = rf(a, b)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(types.AWSResource)
		}
	}

	return r0, r1
}

// NewAWSResourceDescriptorWithPreDeleteDelta creates a new instance of AWSResourceDescriptorWithPreDeleteDelta. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAWSResourceDescriptorWithPreDeleteDelta(t interface {
	mock.TestingT
	Cleanup(func())
}) *AWSResourceDescriptorWithPreDeleteDelta {
	mock := &AWSResourceDescriptorWithPreDeleteDelta{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
