// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	compare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	client "sigs.k8s.io/controller-runtime/pkg/client"

	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/aws-controllers-k8s/runtime/pkg/types"
)

// AWSResourceManager is an autogenerated mock type for the AWSResourceManager type
type AWSResourceManager struct {
	mock.Mock
}

// ARNFromName provides a mock function with given fields: _a0
func (_m *AWSResourceManager) ARNFromName(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ARNFromName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ClearResolvedReferences provides a mock function with given fields: _a0
func (_m *AWSResourceManager) ClearResolvedReferences(_a0 types.AWSResource) types.AWSResource {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ClearResolvedReferences")
	}

	var r0 types.AWSResource
	if rf, ok := ret.Get(0).(func(types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	return r0
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *AWSResourceManager) Create(_a0 context.Context, _a1 types.AWSResource) (types.AWSResource, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 types.AWSResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) (types.AWSResource, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AWSResource) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *AWSResourceManager) Delete(_a0 context.Context, _a1 types.AWSResource) (types.AWSResource, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 types.AWSResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) (types.AWSResource, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AWSResource) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnsureTags provides a mock function with given fields: _a0, _a1, _a2
func (_m *AWSResourceManager) EnsureTags(_a0 context.Context, _a1 types.AWSResource, _a2 types.ServiceControllerMetadata) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for EnsureTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource, types.ServiceControllerMetadata) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterSystemTags provides a mock function with given fields: _a0, _a1
func (_m *AWSResourceManager) FilterSystemTags(_a0 types.AWSResource, _a1 []string) {
	_m.Called(_a0, _a1)
}

// IsSynced provides a mock function with given fields: _a0, _a1
func (_m *AWSResourceManager) IsSynced(_a0 context.Context, _a1 types.AWSResource) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IsSynced")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AWSResource) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LateInitialize provides a mock function with given fields: _a0, _a1
func (_m *AWSResourceManager) LateInitialize(_a0 context.Context, _a1 types.AWSResource) (types.AWSResource, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for LateInitialize")
	}

	var r0 types.AWSResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) (types.AWSResource, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AWSResource) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadOne provides a mock function with given fields: _a0, _a1
func (_m *AWSResourceManager) ReadOne(_a0 context.Context, _a1 types.AWSResource) (types.AWSResource, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReadOne")
	}

	var r0 types.AWSResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) (types.AWSResource, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AWSResource) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResolveReferences provides a mock function with given fields: _a0, _a1, _a2
func (_m *AWSResourceManager) ResolveReferences(_a0 context.Context, _a1 client.Reader, _a2 types.AWSResource) (types.AWSResource, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ResolveReferences")
	}

	var r0 types.AWSResource
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Reader, types.AWSResource) (types.AWSResource, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Reader, types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Reader, types.AWSResource) bool); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, client.Reader, types.AWSResource) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AWSResourceManager) Update(_a0 context.Context, _a1 types.AWSResource, _a2 types.AWSResource, _a3 *compare.Delta) (types.AWSResource, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 types.AWSResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource, types.AWSResource, *compare.Delta) (types.AWSResource, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AWSResource, types.AWSResource, *compare.Delta) types.AWSResource); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AWSResource, types.AWSResource, *compare.Delta) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAWSResourceManager creates a new instance of AWSResourceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAWSResourceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *AWSResourceManager {
	mock := &AWSResourceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
