// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	types "github.com/aws-controllers-k8s/runtime/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// ReferenceEnsurer is an autogenerated mock type for the ReferenceEnsurer type
type ReferenceEnsurer struct {
	mock.Mock
}

// EnsureReferences provides a mock function with given fields: desired, latest
func (_m *ReferenceEnsurer) EnsureReferences(desired types.AWSResource, latest types.AWSResource) types.AWSResource {
	ret := _m.Called(desired, latest)

	if len(ret) == 0 {
		panic("no return value specified for EnsureReferences")
	}

	var r0 types.AWSResource
	if rf, ok := ret.Get(0).(func(types.AWSResource, types.AWSResource) types.AWSResource); ok {
		r0 = rf(desired, latest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	return r0
}

// NewReferenceEnsurer creates a new instance of ReferenceEnsurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReferenceEnsurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReferenceEnsurer {
	mock := &ReferenceEnsurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
