// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"

	types "github.com/aws-controllers-k8s/runtime/pkg/types"
)

// ReferenceManager is an autogenerated mock type for the ReferenceManager type
type ReferenceManager struct {
	mock.Mock
}

// ClearResolvedReferences provides a mock function with given fields: _a0
func (_m *ReferenceManager) ClearResolvedReferences(_a0 types.AWSResource) types.AWSResource {
	ret := _m.Called(_a0)

	var r0 types.AWSResource
	if rf, ok := ret.Get(0).(func(types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	return r0
}

// ResolveReferences provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReferenceManager) ResolveReferences(_a0 context.Context, _a1 client.Reader, _a2 types.AWSResource) (types.AWSResource, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 types.AWSResource
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Reader, types.AWSResource) (types.AWSResource, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Reader, types.AWSResource) types.AWSResource); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.AWSResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Reader, types.AWSResource) bool); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, client.Reader, types.AWSResource) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewReferenceManager creates a new instance of ReferenceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReferenceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReferenceManager {
	mock := &ReferenceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
