// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
)

// SecretReferenceResolver is an autogenerated mock type for the SecretReferenceResolver type
type SecretReferenceResolver struct {
	mock.Mock
}

// SecretReferences provides a mock function with no fields
func (_m *SecretReferenceResolver) SecretReferences() []*v1alpha1.SecretKeyReference {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SecretReferences")
	}

	var r0 []*v1alpha1.SecretKeyReference
	if rf, ok := ret.Get(0).(func() []*v1alpha1.SecretKeyReference); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.SecretKeyReference)
		}
	}

	return r0
}

// NewSecretReferenceResolver creates a new instance of SecretReferenceResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretReferenceResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretReferenceResolver {
	mock := &SecretReferenceResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
