// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TraceExiter is an autogenerated mock type for the TraceExiter type
type TraceExiter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err, additionalValues
func (_m *TraceExiter) Execute(err error, additionalValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, additionalValues...)
	_m.Called(_ca...)
}
