// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// SubResourceClientConstructor is an autogenerated mock type for the SubResourceClientConstructor type
type SubResourceClientConstructor struct {
	mock.Mock
}

// SubResource provides a mock function with given fields: subResource
func (_m *SubResourceClientConstructor) SubResource(subResource string) client.SubResourceClient {
	ret := _m.Called(subResource)

	if len(ret) == 0 {
		panic("no return value specified for SubResource")
	}

	var r0 client.SubResourceClient
	if rf, ok := ret.Get(0).(func(string) client.SubResourceClient); ok {
		r0 = rf(subResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SubResourceClient)
		}
	}

	return r0
}

// NewSubResourceClientConstructor creates a new instance of SubResourceClientConstructor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubResourceClientConstructor(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubResourceClientConstructor {
	mock := &SubResourceClientConstructor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
