// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// NestedObjectEncoder is an autogenerated mock type for the NestedObjectEncoder type
type NestedObjectEncoder struct {
	mock.Mock
}

// EncodeNestedObjects provides a mock function with given fields: e
func (_m *NestedObjectEncoder) EncodeNestedObjects(e runtime.Encoder) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for EncodeNestedObjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(runtime.Encoder) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNestedObjectEncoder creates a new instance of NestedObjectEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNestedObjectEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *NestedObjectEncoder {
	mock := &NestedObjectEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
