// Code generated by mockery v2.19.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// NestedObjectDecoder is an autogenerated mock type for the NestedObjectDecoder type
type NestedObjectDecoder struct {
	mock.Mock
}

// DecodeNestedObjects provides a mock function with given fields: d
func (_m *NestedObjectDecoder) DecodeNestedObjects(d runtime.Decoder) error {
	ret := _m.Called(d)

	var r0 error
	if rf, ok := ret.Get(0).(func(runtime.Decoder) error); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewNestedObjectDecoder interface {
	mock.TestingT
	Cleanup(func())
}

// NewNestedObjectDecoder creates a new instance of NestedObjectDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNestedObjectDecoder(t mockConstructorTestingTNewNestedObjectDecoder) *NestedObjectDecoder {
	mock := &NestedObjectDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
