// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ObjectCreater is an autogenerated mock type for the ObjectCreater type
type ObjectCreater struct {
	mock.Mock
}

// New provides a mock function with given fields: kind
func (_m *ObjectCreater) New(kind schema.GroupVersionKind) (runtime.Object, error) {
	ret := _m.Called(kind)

	var r0 runtime.Object
	if rf, ok := ret.Get(0).(func(schema.GroupVersionKind) runtime.Object); ok {
		r0 = rf(kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.Object)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(schema.GroupVersionKind) error); ok {
		r1 = rf(kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewObjectCreater interface {
	mock.TestingT
	Cleanup(func())
}

// NewObjectCreater creates a new instance of ObjectCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewObjectCreater(t mockConstructorTestingTNewObjectCreater) *ObjectCreater {
	mock := &ObjectCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
