// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ObjectDefaulter is an autogenerated mock type for the ObjectDefaulter type
type ObjectDefaulter struct {
	mock.Mock
}

// Default provides a mock function with given fields: in
func (_m *ObjectDefaulter) Default(in runtime.Object) {
	_m.Called(in)
}
