// Code generated by mockery v2.19.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnstructuredConverter is an autogenerated mock type for the UnstructuredConverter type
type UnstructuredConverter struct {
	mock.Mock
}

// FromUnstructured provides a mock function with given fields: u, obj
func (_m *UnstructuredConverter) FromUnstructured(u map[string]interface{}, obj interface{}) error {
	ret := _m.Called(u, obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, interface{}) error); ok {
		r0 = rf(u, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToUnstructured provides a mock function with given fields: obj
func (_m *UnstructuredConverter) ToUnstructured(obj interface{}) (map[string]interface{}, error) {
	ret := _m.Called(obj)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(interface{}) map[string]interface{}); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUnstructuredConverter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnstructuredConverter creates a new instance of UnstructuredConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnstructuredConverter(t mockConstructorTestingTNewUnstructuredConverter) *UnstructuredConverter {
	mock := &UnstructuredConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
